name: Android Build Release (AAB)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Restaurar Keystore
      run: |
        # Decodifica a chave a partir do segredo
        echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > app/motorista.jks
        
    - name: Verificar Keystore (Debug)
      run: |
        # Lista o arquivo para ver o tamanho
        ls -l app/motorista.jks
        
        # Verifica se o arquivo tem tamanho maior que 0
        if [ ! -s app/motorista.jks ]; then
          echo "❌ ERRO CRÍTICO: O arquivo app/motorista.jks está vazio!"
          echo "Isso significa que o Secret ANDROID_KEYSTORE_BASE64 não foi configurado corretamente no GitHub."
          exit 1
        else
          echo "✅ Keystore restaurada com sucesso. Tamanho ok."
        fi

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.2'

    - name: Build Release AAB (Lint Ignorado)
      run: gradle bundleRelease --stacktrace

    - name: Upload AAB Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-bundle
        path: app/build/outputs/bundle/release/app-release.aab
